16 maj 2018 18:03:24, Exception was thrown: Unable to find -1, since it is not in the catalog.
se.kth.iv1350.PoS.exception.ItemDoesNotExistException: Unable to find -1, since it is not in the catalog.
	at se.kth.iv1350.PoS.integration.ItemCatalog.getItem(ItemCatalog.java:49)
	at se.kth.iv1350.PoS.controller.Controller.enterItem(Controller.java:68)
	at se.kth.iv1350.PoS.view.View.enterItemToSaleByID(View.java:53)
	at se.kth.iv1350.PoS.demo.DemoProcessSale.trySaleProcess(DemoProcessSale.java:24)
	at se.kth.iv1350.PoS.startup.Main.main(Main.java:33)
16 maj 2018 18:03:24, Exception was thrown: Unable to find 500, since it is not in the catalog.
se.kth.iv1350.PoS.exception.ItemDoesNotExistException: Unable to find 500, since it is not in the catalog.
	at se.kth.iv1350.PoS.integration.ItemCatalog.getItem(ItemCatalog.java:49)
	at se.kth.iv1350.PoS.controller.Controller.enterItem(Controller.java:68)
	at se.kth.iv1350.PoS.view.View.enterItemToSaleByID(View.java:53)
	at se.kth.iv1350.PoS.demo.DemoProcessSale.trySaleProcess(DemoProcessSale.java:25)
	at se.kth.iv1350.PoS.startup.Main.main(Main.java:33)
16 maj 2018 18:03:24, Exception was thrown: Could not enter item.
se.kth.iv1350.PoS.exception.OperationFailedException: Could not enter item.
	at se.kth.iv1350.PoS.controller.Controller.enterItem(Controller.java:74)
	at se.kth.iv1350.PoS.view.View.enterItemToSaleByID(View.java:53)
	at se.kth.iv1350.PoS.demo.DemoProcessSale.trySaleProcess(DemoProcessSale.java:37)
	at se.kth.iv1350.PoS.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.PoS.exception.ItemCatalogException: Database failure.
	at se.kth.iv1350.PoS.integration.ItemCatalog.getItem(ItemCatalog.java:43)
	at se.kth.iv1350.PoS.controller.Controller.enterItem(Controller.java:68)
	... 3 more
